hydrus:
  restart: always
  build: ./
  ports:
    - "8080:80"
  environment:
    - HYDRUS_SERVER_URL=http://192.168.99.100:8080/
  links:
    - postgres:postgres

postgres:
  restart: always
  environment:
    - POSTGRES_USER=hydra
    - POSTGRES_PASSWORD=hailhydra
    - POSTGRES_DB=hydrus
  image: postgres:latest
  ports:
    - "9000:5432"
